# .github/workflows/ci-cd-pipeline.yml

name: CI/CD Pipeline - API Plataforma Profissional

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # ===================================================================
  # JOB 1: BUILD E TESTES AUTOMATIZADOS
  # ===================================================================
  build-and-test:
    name: Build, Test e Package
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' 
          distribution: 'temurin'
          cache: 'maven' 

      - name: Tornar o Maven Wrapper executável
        run: chmod +x mvnw

      - name: Build com Maven Wrapper
        run: ./mvnw clean install 

      - name: Upload dos Relatórios de Teste
        if: always() 
        uses: actions/upload-artifact@v4
        with:
          name: relatorios-de-teste
          path: target/surefire-reports/
          
      # Não precisamos salvar o .jar se não vamos fazer deploy
      # Mas vamos manter, caso você queira baixá-lo manualmente
      - name: Upload do Artefato da Aplicação (.jar)
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar 

  # ===================================================================
  # JOB 2: ATUALIZAÇÃO DO BANCO DE DADOS ORACLE
  # ===================================================================
  run-database-migration: # <-- NOME MUDOU (era deploy-and-migrate)
    name: Atualizar Banco de Dados Oracle
    runs-on: ubuntu-latest
    
    needs: build-and-test 
    
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'

    steps:
      # 1. Download do código (precisamos do script SQL)
      - name: Checkout do código
        uses: actions/checkout@v4
        
      # 2. INTEGRAÇÃO ORACLE: Executa o script SQL (SQL_PPA_2.sql)
      - name: Executar Migração do Banco Oracle
        uses: diliver/action-sqlplus@v1  # <-- Usando a action correta
        with:
          user: ${{ secrets.ORACLE_USER }}
          password: ${{ secrets.ORACLE_PASSWORD }}
          connection_string: ${{ secrets.ORACLE_CONNECT_STRING }}
          sql: SQL_PPA_2.sql # O script que criamos

      # --- ETAPAS DE DEPLOY REMOVIDAS ---
      # 4. Deploy para Servidor via SCP  <-- REMOVIDO
      # 5. Reiniciar Serviço da API      <-- REMOVIDO
